# Generated by Django 4.2.7 on 2023-12-27 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_invoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='price',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='quantity',
            field=models.IntegerField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='quantity',
            field=models.IntegerField(max_length=10, null=True),
        ),
    ]
